### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [Mariosmsk/QLocklayers#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by Mariosmsk** [comment]
Hi @pcav, this plugin can be used to set many selected layers to removable or to no removable, quickly.  Also, I have a video here: [https://www.youtube.com/watch?v=kNYlnBAeoD8](https://www.youtube.com/watch?v=kNYlnBAeoD8).  Thanks.

**Comment by pcav** [comment]
Thanks
